version: '3'

services:
        php-apache:
            build:
                context: ./docker/php-apache
                args:
                    - nginx_host=${NGINX_HOST}
            volumes:
                - ./.data/html:/var/www/html:rw
            ports:
                - "80:80"
                - "443:443"
            env_file:
                - .env
        python:
            build:
                context: ./docker/python
            depends_on:
                - mongodb
            env_file:
                - .env
        mongodb:
            build:
                context: ./docker/mongodb
                args:
                    - mongodb_username=${MONGODB_USERNAME}
                    - mongodb_password=${MONGODB_PASSWORD}
                    - mongodb_initdb_database=${MONGO_INITDB_DATABASE}
            volumes:
                - ./.data/mongo:/data/db:rw
            env_file:
                - .env
            ports:
                - "27017:27017"
            